id: 7771e9ab5af942a09433be3f82b1f628
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_147-The_Teaching_on_the_Great_Compassion_of_the_Tathagata-v1
  language: en
  author: ''
  volume: {}
